name: Check Branch Naming

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo "${{ github.head_ref }}")
          if [[ ! "$BRANCH_NAME" =~ ^(feat|ref|fix|bug):[0-9]+-.+ ]]; then
            echo "Branch name does not match the required pattern."
            exit 1
          fi
